name: RemielCore
main: me.taylan.mooncore.MoonCore
version: 1.0.0
api-version: 1.18
author: Taylan
depend: [CrazyAdvancementsAPI, CoreProtect]

commands:
   ustalık:
   discord:
   statekle:
   profil:
   seviye:
   bookver:
   nitelik:
   claimset:
   back:
   oynanansure: